# Generated by Django 4.1.1 on 2022-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(max_length=128, upload_to='tosend/'),
        ),
    ]
